# Generated by Django 2.1.1 on 2018-11-05 01:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='users',
            old_name='emailID',
            new_name='email',
        ),
        migrations.AlterField(
            model_name='passwords',
            name='userID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainApp.Users', to_field='emailID'),
        ),
        migrations.AlterField(
            model_name='website',
            name='user_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainApp.Users', to_field='emailID'),
        ),
    ]
