# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-11-06 06:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='passwords',
            old_name='passwords',
            new_name='password',
        ),
    ]
