# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-11-11 01:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0002_auto_20181105_2234'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='passwords',
            name='userID',
        ),
        migrations.RemoveField(
            model_name='passwords',
            name='websiteID',
        ),
        migrations.AddField(
            model_name='website',
            name='password',
            field=models.CharField(default='SOME STRING', help_text='Enter field documentation', max_length=100),
        ),
        migrations.DeleteModel(
            name='Passwords',
        ),
    ]
