# Generated by Django 2.1.1 on 2018-11-05 01:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0002_auto_20181104_1750'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwords',
            name='userID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainApp.Users'),
        ),
        migrations.AlterField(
            model_name='website',
            name='user_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainApp.Users'),
        ),
    ]
