# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-11-12 00:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0003_auto_20181110_1713'),
    ]

    operations = [
        migrations.AlterField(
            model_name='website',
            name='password',
            field=models.CharField(help_text='Enter field documentation', max_length=100),
        ),
    ]
