# Generated by Django 2.1.1 on 2018-10-23 23:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Passwords',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userID', models.CharField(max_length=20)),
                ('emailID', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Website',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('website_ID', models.CharField(max_length=20)),
                ('urlNAME', models.CharField(max_length=20)),
                ('websiteName', models.CharField(max_length=20)),
                ('desc', models.CharField(max_length=20)),
                ('category', models.CharField(max_length=20)),
                ('user_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sketchtools.Users')),
            ],
        ),
        migrations.AddField(
            model_name='passwords',
            name='userID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sketchtools.Users'),
        ),
        migrations.AddField(
            model_name='passwords',
            name='websiteID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sketchtools.Website'),
        ),
    ]
